#!/usr/bin/env python
#encoding:utf-8

import cv2
import os
import matplotlib.pyplot as plt
import numpy as np
import random
import string

characters = string.ascii_uppercase
undistinct = 'CKOPSVZ'
chars = characters
for i in characters:
    if i not in undistinct:
        chars += i.lower()
print(chars)

width, height, n_len, n_class = 130, 53, 4, len(chars)
path = os.getcwd() + '/sample3'
print path

for root, dirs, files in os.walk(path):
    print root
    print dirs
    print len(files)
root, dirs, files = os.walk(path).next()
print root
print dirs
print len(files)

print '-'*70
for i in files:
    print i

def gen(batch_size=32):
    X = np.zeros((batch_size, height, width, 3), dtype=np.uint8)
    y = [np.zeros((batch_size, n_class), dtype=np.uint8) for i in range(n_len)]
    root, dirs, files = os.walk(path).next()
    cnt = 0
    while cnt < len(files):
        for i in range(batch_size):
            image = files[cnt]
            X[i] = cv2.imread(root+'/'+image)
            cnt += 1
            for j, ch in enumerate(image[:4]):
                y[j][i, :] = 0
                y[j][i, chars.find(ch)] = 1
        yield X, y
        
def decode(y):
    y = np.argmax(np.array(y), axis=2)[:,0]
    return ''.join([chars[x] for x in y])
a = gen(2)
X, y = a.next()
plt.imshow(X[0])
plt.title(decode(y))
plt.show()

while 1:
    X, y = a.next()
    plt.imshow(X[0])
    plt.title(decode(y))
    plt.show()    